version: '3.5'

services:
  postgres:
    container_name: postgres_container_typeorm
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5050
      POSTGRES_DB: typeorm
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '54325:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
